# Generated by Django 2.0.5 on 2018-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='media/images/'),
        ),
    ]
